<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dokumen</name>
   <tag></tag>
   <elementGuidId>85f3fa14-0dd1-461d-9149-d6ba6c7a8087</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainnav']/ul/li[6]/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.nav-submenu.menu-content > li:nth-of-type(2) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d395bad-20e9-4c6e-9698-ac95bbf123fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://130.211.243.37:96/library/dokumen</value>
      <webElementGuid>d939ca8d-dc11-49df-a6ec-6b31e8109b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dokumen</value>
      <webElementGuid>da7e1f4d-bbd3-4bfe-b791-1a4418c3c459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainnav&quot;)/ul[@class=&quot;nav-menu custom-scrollbar&quot;]/li[@class=&quot;dropdown&quot;]/ul[@class=&quot;nav-submenu menu-content&quot;]/li[2]/a[1]</value>
      <webElementGuid>b49247c1-22e3-40ca-8e47-84d288988e5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainnav']/ul/li[6]/ul/li[2]/a</value>
      <webElementGuid>64e9acb3-7e0a-4a09-b218-7014c6f69e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dokumen')]</value>
      <webElementGuid>05870d23-5b38-4469-adb9-89f59a8726df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://130.211.243.37:96/library/dokumen']</value>
      <webElementGuid>b68dc3fb-6efe-4c52-8b95-dc2a310989d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li[2]/a</value>
      <webElementGuid>9794a84d-3e99-4273-8976-9d905b4cedd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://130.211.243.37:96/library/dokumen' and (text() = 'Dokumen' or . = 'Dokumen')]</value>
      <webElementGuid>7e6c5e65-1da8-4568-83d9-6b85e59a26bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
